version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    environment:
      SERVICE_LABEL: dutch_lady_onboarding_scheduling
    expose:
      - '4200'
    ports:
      - '4200:4200'
