name: Pipeline for branches

env:
  MAX_SIZE_UPLOAD: 5000
  ADMIN_SERVICE_URL: http://localhost:8080/user
  API_SECRET: abcxyz
  STS_JWT: abc123

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches-ignore:
      - "**"
  pull_request_target:

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - name: "Install NPM dependencies"
        run: npm ci
      - name: "Static checks"
        if: github.ref == 'refs/heads/master'
        run: npm run test:lint
      - name: "Unit tests"
        run: npm run test:unit
      - name: "Acceptance tests"
        run: npm run test:acceptance

  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - name: "Install NMP dependencies"
        run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Build, tag, and push image to Amazon ECR
        run: |
          cp .env.example .env
          source .env

          export BRANCH_TAG=$(echo "${SERVICE_LABEL}-v-${{ steps.package-version.outputs.current-version}}" | sed -E 's/([^0-9a-zA-Z.]+)/-/g' | awk '{print tolower($0)}')

          docker build -t $ECR_REPOSITORY .

          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:dutch-lady-v-0.0.1
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dutch-lady-v-0.0.1
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}
        env:
          ECR_REGISTRY: 942095822719.dkr.ecr.eu-west-2.amazonaws.com
          ECR_REPOSITORY: kidsloop-vietnam-onboarding
